management:
  security:
    enabled: false 

spring:
  cloud:
    services:
      registrationMethod: direct

security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal:
        training: INFO 
